### ISSUE TITLE
Fatal Crash - Crashed Error Recovery Also

### ISSUE THREAD

**Issue by pkahly** [pkahly/bitcoin-monitor#31]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa974e71fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cryptowat.ch', port=443): Max retries exceeded with url: /markets/gdax/btcusd/price (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa974e71fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philip/coding/bitcoin/bitcoin-monitor/lib/bitcoin_alerter.py", line 46, in run_bitcoin_alerter_with_exponential_backoff
    run_bitcoin_alerter()
  File "/home/philip/coding/bitcoin/bitcoin-monitor/lib/bitcoin_alerter.py", line 16, in run_bitcoin_alerter
    info = info_collector.get_info(previous_info)
  File "/home/philip/coding/bitcoin/bitcoin-monitor/lib/info_collector.py", line 74, in get_info
    priceResponse = requests.get("https://api.cryptowat.ch/markets/gdax/btcusd/price")
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cryptowat.ch', port=443): Max retries exceeded with url: /markets/gdax/btcusd/price (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa974e71fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 64, in <module>
    bitcoin_alerter.run_bitcoin_alerter_with_exponential_backoff()
  File "/home/philip/coding/bitcoin/bitcoin-monitor/lib/bitcoin_alerter.py", line 49, in run_bitcoin_alerter_with_exponential_backoff
    email.send_email("Bitcoin Monitor Has Crashed", str(ex))
  File "/home/philip/coding/bitcoin/bitcoin-monitor/lib/email.py", line 15, in send_email
    server = smtplib.SMTP_SSL(SERVER,port=PORT)
  File "/usr/lib/python3.6/smtplib.py", line 1031, in __init__
    source_address)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 1037, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by pkahly** [comment]
Adding a nested try-except for the crash report email, with a log message of "Failed to send crash report" on failure.

That should prevent this issue in the future.
