### ISSUE TITLE
Error With Clean Install

### ISSUE THREAD

**Issue by pkahly** [pkahly/bitcoin-monitor#36]
Traceback (most recent call last):
  File "./main.py", line 66, in <module>
    install_menu()     
  File "./main.py", line 22, in install_menu
    install.add_blocks()
  File "/home/philip/Desktop/bitcoin-monitor/lib/install.py", line 55, in add_blocks
    reorg_info = reorg.add_blocks()
  File "/home/philip/Desktop/bitcoin-monitor/lib/reorg.py", line 43, in add_blocks
    highest_stored_block = get_highest_stored_block(cursor)
  File "/home/philip/Desktop/bitcoin-monitor/lib/reorg.py", line 10, in get_highest_stored_block
    return cursor.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by pkahly** [comment]
Fixed most of the fresh install issues. 

Still seeing a problem with historical data though.

**Comment by pkahly** [comment]
Turns out that was a problem introduced by these fixes.
