### ISSUE TITLE
import_historical_prices() Should Not Attempt to Overwrite Existing Dates

### ISSUE THREAD

**Issue by pkahly** [pkahly/bitcoin-monitor#37]
Traceback (most recent call last):
  File "./main.py", line 66, in <module>
    install_menu()     
  File "./main.py", line 20, in install_menu
    install.import_historical_prices()
  File "/home/philip/Desktop/bitcoin-monitor/lib/install.py", line 97, in import_historical_prices
    cursor.execute(sql_command)
sqlite3.IntegrityError: UNIQUE constraint failed: historical_prices.date
philip@Mark4:~/Desktop/bitcoin-monitor$

**Comment by pkahly** [comment]
It should check for the most recent date and stop when it reaches it.
