### ISSUE TITLE
BrokenPipeError Trying to Access Bitcoin Client

### ISSUE THREAD

**Issue by pkahly** [pkahly/bitcoin-monitor#75]
Traceback (most recent call last):
  File "./main.py", line 66, in <module>
    bitcoin_alerter.run_bitcoin_alerter()
  File "/home/philip/coding/bitcoin-monitor/lib/bitcoin_alerter.py", line 17, in run_bitcoin_alerter
    _run()
  File "/home/philip/coding/bitcoin-monitor/lib/bitcoin_alerter.py", line 24, in _run
    info = info_collector.get_info(previous_info)
  File "/home/philip/coding/bitcoin-monitor/lib/info_collector.py", line 24, in get_info
    info.blocks = bitcoin_node_api.get_num_blocks()
  File "/home/philip/coding/bitcoin-monitor/lib/bitcoin_node_api.py", line 21, in get_num_blocks
    return client.getblockcount()
  File "/home/philip/.local/lib/python3.6/site-packages/bitcoinrpc/authproxy.py", line 136, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by pkahly** [comment]
We need to close the client object in bitcoin_node_api.py when we're done using it, then open a new one on the next iteration.

Perhaps we should encapsulate bitcoin_node_api's functions and the module-level client parameter in a class. 

info_collector.py would create a new instance of that class, thereby recreating the client, each time it runs.
