### ISSUE TITLE
Intermittent Timestamp Uniqueness Error

### ISSUE THREAD

**Issue by pkahly** [pkahly/bitcoin-monitor#78]
Traceback (most recent call last):
  File "./main.py", line 66, in <module>
    bitcoin_alerter.run_bitcoin_alerter()
  File "/home/philip/coding/bitcoin-monitor/lib/bitcoin_alerter.py", line 17, in run_bitcoin_alerter
    _run()
  File "/home/philip/coding/bitcoin-monitor/lib/bitcoin_alerter.py", line 37, in _run
    info_collector.write_info(info)
  File "/home/philip/coding/bitcoin-monitor/lib/info_collector.py", line 118, in write_info
    cursor.execute(sql_command)
sqlite3.IntegrityError: UNIQUE constraint failed: status_info.timestamp

**Comment by pkahly** [comment]
It's supposed to be sleeping 5 minutes in between....
